### ISSUE TITLE
progress

### ISSUE THREAD

**Issue by lx-0713** [likaiyuan559/TikTokDemo#18]
public native void combine(ArrayList<VideoInfo> videoInfos, String audioPath, double weight1, double weight2, String outputVideoPath, VideoListener listener);

这个方法没有调用到  VideoListener的onProgress(String outputPath, int percentage);方法，所以不能计算完成的百分比。

**Comment by likaiyuan559** [comment]
这是一个理论上不存在的bug，建议自查是否打印错了地方，如果确定是bug，请贴出详细log和信息。

**Comment by lx-0713** [comment]
![image](https://user-images.githubusercontent.com/18158571/59660720-d8a3f580-91db-11e9-88bb-805047fb0eaa.png)

**Comment by lx-0713** [comment]
这个是jni的源码中没有调用的问题
