### ISSUE TITLE
楼主可否将其他cpu架构的共享库补齐？或者共享源码给我们自己编译生成其他平台的共享库

### ISSUE THREAD

**Issue by chat491231702** [likaiyuan559/TikTokDemo#6]
目前只提供了armeabi，为了实际应用需求，希望可以提供 arm64-v8a、armeabi-v7a、x86、x86_64、mips、mips_64平台架构的so

**Comment by likaiyuan559** [comment]
其实一般只用到armeabi及armeabi-v7a

**Comment by 1741470774** [comment]
> 其实一般只用到armeabi及armeabi-v7a

@likaiyuan559 你好，希望提供下其他架构的so库，有偿。有意联系wx：15880080743，备注：Tik Tok demo
