### ISSUE TITLE
楼主  有的视频解析失败是怎么回事，HeyhouVideo.getMetaInfo(mVideoPath,mateInfo);执行之后得到的mateInfo还是空，这里是不是jni方法的问题，可以再完善一下吗，因为同样是MP4视频，有的可以，有的不可以。

### ISSUE THREAD

**Issue by fengxiaobing** [likaiyuan559/TikTokDemo#9]
楼主  有的视频解析失败是怎么回事，HeyhouVideo.getMetaInfo(mVideoPath,mateInfo);执行之后得到的mateInfo还是空，这里是不是jni方法的问题，可以再完善一下吗，因为同样是MP4视频，有的可以，有的不可以。这个问题不清楚

**Comment by likaiyuan559** [comment]
麻烦过滤log --> "heyhou"，把打印信息一起附上。

**Comment by fengxiaobing** [comment]
![image](https://user-images.githubusercontent.com/19527691/55310915-3f92f780-5494-11e9-89ff-dff5fb2a1c87.png)
是没有发现音频吗？这个视频是我拿录屏大师录制的，可能是没有打开音频录制

**Comment by likaiyuan559** [comment]
请提供log，不然将会关闭问题。

**Comment by fengxiaobing** [comment]
04-01 15:37:34.683 27090-27090/com.tiktokdemo.lky.tiktokdemo E/HeyhouVideo.cpp: Cannot find a audio stream in the input file,ret=-1381258232,error=Stream not found
04-01 15:37:34.683 27090-27090/com.tiktokdemo.lky.tiktokdemo E/HeyhouVideo.cpp: open input video file fail
04-01 15:37:34.683 27090-27090/com.tiktokdemo.lky.tiktokdemo E/HeyhouVideo.cpp: get meta info fail
04-01 15:37:34.684 27090-27339/com.tiktokdemo.lky.tiktokdemo D/HeyhouPlayerService: set position-----------
04-01 15:37:34.684 27090-27339/com.tiktokdemo.lky.tiktokdemo E/HeyhouVideo.cpp: player have inited
04-01 15:37:34.707 27090-27339/com.tiktokdemo.lky.tiktokdemo D/HeyhouPlayerService: ------------prepare--------------
04-01 15:37:34.707 27090-27339/com.tiktokdemo.lky.tiktokdemo E/HeyhouVideo.cpp: set new render
04-01 15:37:34.707 27090-27339/com.tiktokdemo.lky.tiktokdemo E/HeyhouVideo.cpp: set new listener
04-01 15:37:34.707 27090-27339/com.tiktokdemo.lky.tiktokdemo E/HeyhouVideo.cpp: player have inited
04-01 15:37:34.707 27090-27339/com.tiktokdemo.lky.tiktokdemo E/HeyhouVideo.cpp: load media stream /storage/emulated/0/lkyDemo/RBB.mp4
04-01 15:37:34.759 27090-27339/com.tiktokdemo.lky.tiktokdemo E/HeyhouVideo.cpp: Cannot find audio stream




图片上传显示不出来吗  这是日志

**Comment by likaiyuan559** [comment]
暂不支持不带音轨的视频文件处理。
